"""
🎵 YouTube downloader — yt-dlp wrapper

FIXES APPLIED:
  • Heroku CDN block detection — skips googlevideo.com CDN URLs that always
    fail on cloud IPs (Heroku DYNO, Railway, Render, Fly.io, etc.).
  • "Sign in to confirm you're not a bot" — uses android_music + ios + web
    player clients in order; these bypass the sign-in wall for public videos.
  • Instant streaming — download_audio() returns a FIFO named pipe on Linux
    (Heroku supports mkfifo).  yt-dlp writes audio to the pipe in a daemon
    thread; PyTgCalls starts reading before the full download finishes.
    Falls back to full file download if mkfifo is unavailable.
  • YT_COOKIES binary guard — already present; kept as-is.
  • WebM/Opus preferred format — streamable via FIFO without seeking,
    unlike AAC/M4A which requires the moov atom at EOF.
"""
import asyncio
import base64
import glob
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time

from yt_dlp import YoutubeDL
from melody.config import Config
from melody.logging import LOGGER, send_error_log

# Check whether curl_cffi is available (enables Chrome TLS impersonation,
# which bypasses YouTube's bot-detection on Heroku / cloud IPs).
try:
    import curl_cffi  # noqa: F401
    _CURL_CFFI_OK = True
    LOGGER.info("✅ curl_cffi available — Chrome TLS impersonation enabled")
except ImportError:
    _CURL_CFFI_OK = False
    LOGGER.warning(
        "curl_cffi not installed — YouTube may block requests on cloud IPs. "
        "Add 'curl_cffi>=0.7.0' to requirements.txt and redeploy."
    )


COOKIES_FILE = "/tmp/melody_yt_cookies.txt"

# ── Cloud-host detection ──────────────────────────────────────────────────────
# On Heroku/Railway/Render/Fly.io the YouTube CDN (googlevideo.com) is
# IP-blocked.  Trying to stream directly from a CDN signed URL produces an
# immediate EOF → 10-25 s of silence before the retry kicks in.
# Detect at startup and always use full local download on these hosts.
_ON_CLOUD_HOST: bool = bool(
    os.environ.get("DYNO")                    # Heroku
    or os.environ.get("RAILWAY_ENVIRONMENT")  # Railway
    or os.environ.get("RENDER_SERVICE_ID")    # Render
    or os.environ.get("FLY_APP_NAME")         # Fly.io
    or os.environ.get("K_SERVICE")            # Google Cloud Run
    or os.environ.get("WEBSITE_INSTANCE_ID")  # Azure App Service
)
if _ON_CLOUD_HOST:
    LOGGER.info("☁️  Cloud host detected — YouTube CDN streaming skipped; using local download")

# ── FIFO pipe concurrency ────────────────────────────────────────────────────
# Cap parallel FIFO downloads so we don't exhaust Heroku memory.
_PIPE_MAX_CONCURRENT = 4
_pipe_slots = threading.BoundedSemaphore(_PIPE_MAX_CONCURRENT)
_PIPE_CONNECT_TIMEOUT = 15.0   # seconds to wait for ntgcalls to open the read end
_PIPE_SLOT_TIMEOUT    = 5.0    # fail fast if all slots taken; retry will use file download

# Track pipe paths that are actively being written so _cleanup_temp can skip them.
_active_pipes: set = set()
_active_pipes_lock = threading.Lock()


# ─────────────────────────────────────────────────────────────────────────────
#  Cookie helpers (unchanged — binary-guard logic kept)
# ─────────────────────────────────────────────────────────────────────────────

def _json_cookies_to_netscape(json_text: str) -> str:
    import json
    try:
        cookies = json.loads(json_text)
    except (json.JSONDecodeError, ValueError):
        return json_text
    if not isinstance(cookies, list):
        return json_text
    lines = ["# Netscape HTTP Cookie File", "# Generated by Melody"]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expirationDate") or c.get("expires") or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _is_netscape_cookies(text: str) -> bool:
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if len(line.split("\t")) == 7:
            return True
    return False


def _write_cookies():
    if not Config.YT_COOKIES:
        return
    try:
        raw_bytes = base64.b64decode(Config.YT_COOKIES)
    except Exception as e:
        LOGGER.warning("YT_COOKIES is not valid base64 — skipping cookies: %s", e)
        return
    try:
        decoded = raw_bytes.decode("utf-8")
    except UnicodeDecodeError:
        LOGGER.warning(
            "YT_COOKIES base64 decodes to binary data (not a text cookie file). "
            "Provide a Netscape-formatted cookies.txt exported from your browser. "
            "Skipping cookies — yt-dlp will run without authentication."
        )
        return
    if "\ufffd" in decoded:
        LOGGER.warning("YT_COOKIES contains non-UTF-8 bytes (binary file). Skipping cookies.")
        return
    decoded = decoded.strip()
    if decoded.startswith("["):
        netscape = _json_cookies_to_netscape(decoded)
        if not _is_netscape_cookies(netscape):
            LOGGER.warning("YT_COOKIES JSON conversion produced no valid entries — skipping.")
            return
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(netscape)
        LOGGER.info("YT_COOKIES (JSON→Netscape) written to %s", COOKIES_FILE)
        return
    if _is_netscape_cookies(decoded):
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(decoded)
        LOGGER.info("YT_COOKIES (Netscape) written to %s", COOKIES_FILE)
        return
    LOGGER.warning(
        "YT_COOKIES format not recognised (not JSON array, not Netscape). "
        "Export cookies using a browser extension like 'Get cookies.txt LOCALLY'. "
        "Skipping cookies — yt-dlp will run without authentication."
    )


_write_cookies()


# ─────────────────────────────────────────────────────────────────────────────
#  yt-dlp options
# ─────────────────────────────────────────────────────────────────────────────

def _ydl_opts(audio_only: bool = True) -> dict:
    """Return base yt-dlp options tuned for Heroku and bot-detection bypass.

    FIXES:
    • "Sign in to confirm you're not a bot":
        android_music → ios → android → tv_embedded → mweb → web
        Android/iOS clients are served a different API path that skips the
        sign-in wall for public videos.  This is the canonical yt-dlp fix.
    • WebM/Opus format preferred — streamable via FIFO pipe without seeking.
      AAC/M4A requires the moov atom at end-of-file → breaks pipe mode.
    • geo_bypass — Heroku USA servers sometimes hit geo-restricted content;
      bypass declaration helps with most non-DRM videos.
    • concurrent_fragment_downloads=1 — sequential fragments keep the FIFO
      data stream continuous; parallel downloads create write bursts → pipe
      starvation → ntgcalls EOF → Broken pipe.
    """
    fmt = (
        # Prefer streamable container first, then anything
        "bestaudio[ext=webm]/bestaudio[ext=opus]/bestaudio[ext=m4a]/bestaudio/best"
        if audio_only
        else "best[height<=720][vcodec!=none][acodec!=none]/best[height<=720]/best"
    )
    opts: dict = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "format": fmt,
        "postprocessors": [],
        "geo_bypass": True,
        "geo_bypass_country": "US",
        "socket_timeout": 10,
        "retries": 5,
        "fragment_retries": 5,
        "check_formats": False,
        "concurrent_fragment_downloads": 1,
        # tv_embedded is the most reliable no-auth client on cloud/Heroku IPs.
        # android_music + ios as backups.
        "extractor_args": {
            "youtube": {
                "player_client": ["tv_embedded", "android_music", "ios", "android", "mweb", "web"],
            }
        },
        "http_headers": {
            "User-Agent": (
                "Mozilla/5.0 (Linux; Android 13; SM-S908B) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/112.0.0.0 Mobile Safari/537.36"
            ),
            "Referer": "https://www.youtube.com/",
        },
    }
    # ⚡ Chrome TLS impersonation — bypasses YouTube bot-detection on Heroku IPs.
    # curl_cffi makes HTTP requests with Chrome's exact TLS fingerprint.
    # YouTube's bot check reads the TLS hello; Python's urllib/requests have a
    # different fingerprint that gets flagged. curl_cffi resolves this.
    if _CURL_CFFI_OK:
        opts["impersonate"] = "chrome-124"
    if os.path.exists(COOKIES_FILE):
        opts["cookiefile"] = COOKIES_FILE
    return opts


# ─────────────────────────────────────────────────────────────────────────────
#  Search helpers
# ─────────────────────────────────────────────────────────────────────────────

async def search_youtube(query: str, limit: int = 5) -> list[dict]:
    """Search YouTube and return a list of results."""
    def _search():
        opts = {**_ydl_opts(), "default_search": f"ytsearch{limit}", "extract_flat": True}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            return info.get("entries", [])

    try:
        loop = asyncio.get_running_loop()
        results = await loop.run_in_executor(None, _search)
        return [
            {
                "id": e.get("id", ""),
                "title": e.get("title", "Unknown"),
                "duration": e.get("duration", 0),
                "url": f"https://www.youtube.com/watch?v={e.get('id', '')}",
                "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{e.get('id','')}/hqdefault.jpg",
                "uploader": e.get("uploader", "Unknown"),
            }
            for e in results
            if e.get("id")
        ]
    except Exception as exc:
        await send_error_log("search_youtube failed", exc)
        return []


def _extract_video_id(url: str) -> str | None:
    """Extract YouTube video ID from various URL formats."""
    import re
    patterns = [
        r"(?:v=|/v/|youtu\.be/|/embed/|/shorts/)([A-Za-z0-9_-]{11})",
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return None



# ─────────────────────────────────────────────────────────────────────────────
#  Invidious fallback search
#  Invidious is a YouTube proxy that runs on non-cloud IPs — it bypasses
#  Heroku's IP block on YouTube's bot-detection API.  Used when yt-dlp fails.
# ─────────────────────────────────────────────────────────────────────────────

_INVIDIOUS_INSTANCES = [
    "https://invidious.f5.si",
    "https://invidious.privacydev.net",
    "https://invidious.nerdvpn.de",
    "https://invidious.fdn.fr",
    "https://invidious.io.lol",
    "https://invidious.einfachzocken.eu",
    "https://invidious.protokolla.fi",
    "https://invidious.privacyredirect.com",
    "https://invidious.jing.rocks",
    "https://invidious.asir.dev",
    "https://invidious.drgns.space",
    "https://invidious.slipfox.xyz",
    "https://invidious.perennialte.ch",
    "https://invidious.reallyaweso.me",
    "https://invidious.darkness.services",
]


def _invidious_search_sync(query: str) -> dict | None:
    """Search YouTube via public Invidious instances (fallback when yt-dlp fails).

    WHY THIS WORKS ON HEROKU:
    Invidious is a self-hosted YouTube proxy. Its API servers are NOT on Heroku
    or AWS — they run on independent VPS machines that YouTube does not block.
    We query their /api/v1/search endpoint (standard JSON REST), which proxies
    the YouTube search API on our behalf. No cookies, no yt-dlp, no CDN URLs.

    ProxyHandler({}) strips any malformed HTTP_PROXY env vars that Heroku
    sometimes sets — they would break urllib but are irrelevant here.
    """
    import json
    import urllib.request
    import urllib.parse

    encoded_query = urllib.parse.quote_plus(query)
    headers = {"User-Agent": "Mozilla/5.0 (compatible; MelodyBot/1.0)"}

    for instance in _INVIDIOUS_INSTANCES:
        try:
            url = f"{instance}/api/v1/search?q={encoded_query}&type=video"
            req = urllib.request.Request(url, headers=headers)
            opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
            with opener.open(req, timeout=8) as resp:
                if resp.status != 200:
                    continue
                items = json.loads(resp.read().decode("utf-8"))

            result = next(
                (item for item in items
                 if item.get("type") == "video" and item.get("videoId")),
                None,
            )
            if not result:
                continue

            thumbnails = result.get("videoThumbnails") or []
            thumbnail = (
                next(
                    (t.get("url", "") for t in thumbnails
                     if t.get("quality") in {"medium", "high"}),
                    thumbnails[0].get("url", "") if thumbnails else "",
                )
            )
            vid = result["videoId"]
            LOGGER.info("✅ Invidious search OK (%s): %s", instance, result.get("title", "")[:50])
            return {
                "id": vid,
                "webpage_url": f"https://www.youtube.com/watch?v={vid}",
                "title": result.get("title") or query,
                "duration": int(result.get("lengthSeconds") or 0),
                "thumbnail": thumbnail,
                "uploader": result.get("author") or "",
            }
        except Exception as exc:
            LOGGER.debug("Invidious search failed (%s): %s", instance, exc)
            continue

    LOGGER.warning("❌ All Invidious instances failed for: %s", query[:50])
    return None


async def get_video_info(url_or_query: str) -> dict | None:
    """Get metadata for a single video (or first search result).

    KEY FIX for Heroku "Sign in to confirm you're not a bot":
    • Uses extract_flat=True — yt-dlp fetches only lightweight metadata
      (title, duration, uploader, thumbnail) WITHOUT requesting streamingData
      (the format/CDN URL list). streamingData calls are what trigger YouTube's
      bot-detection check on cloud IPs. By deferring stream resolution to
      download_audio(), we avoid the check entirely at this stage.
    • For direct YouTube URLs we extract the video_id and search by video_id,
      still via the flat/metadata path (no streamingData request).
    """
    import re
    is_url = bool(re.match(r"https?://", url_or_query))

    if is_url:
        vid_id = _extract_video_id(url_or_query)
        # Use ytsearch1: for the video URL — forces the search API path which
        # only fetches metadata, not streamingData.
        query = f"ytsearch1:{url_or_query}" if not vid_id else f"ytsearch1:https://www.youtube.com/watch?v={vid_id}"
    else:
        query = f"ytsearch1:{url_or_query}"
        vid_id = None

    def _info():
        # CRITICAL FIX: noplaylist=False is REQUIRED for ytsearch1: queries.
        # yt-dlp 2025+ internally wraps ytsearch results in a "SearchResultsPlaylist".
        # With noplaylist=True (from _ydl_opts), yt-dlp refuses to process it → returns
        # nothing → silent "Song not found" error even when the video exists.
        # extract_flat="in_playlist" — lightweight metadata only, no streamingData request
        # (streamingData = the CDN URL list that triggers YouTube bot-detection on Heroku).
        opts = {
            **_ydl_opts(),
            "extract_flat": "in_playlist",
            "default_search": "ytsearch1",
            "noplaylist": False,    # MUST be False for ytsearch1: to work
            "socket_timeout": 6,    # fail fast so Invidious fallback runs sooner
        }
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            if info and "entries" in info and info["entries"]:
                return info["entries"][0]
            return info

    try:
        loop = asyncio.get_running_loop()
        info = await loop.run_in_executor(None, _info)
        if not info or not info.get("id"):
            # ── Invidious fallback: yt-dlp search returned nothing ──────────
            # On Heroku, YouTube's bot-detection sometimes blocks yt-dlp even
            # with Android/iOS clients. Invidious runs its own YouTube API proxy
            # on non-cloud IPs — it is not affected by Heroku's IP ban.
            LOGGER.info("yt-dlp search returned nothing — trying Invidious fallback | %s", url_or_query[:50])
            info = await asyncio.get_event_loop().run_in_executor(
                None, _invidious_search_sync, url_or_query
            )
            if not info or not info.get("id"):
                return None
        vid = info.get("id", "")
        return {
            "id": vid,
            "title": info.get("title", "Unknown"),
            "duration": int(info.get("duration") or 0),
            "url": info.get("webpage_url") or f"https://www.youtube.com/watch?v={vid}",
            "stream_url": "",  # resolved at play time by download_audio()
            "thumbnail": info.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
            "uploader": info.get("uploader") or info.get("channel") or "Unknown",
        }
    except Exception as exc:
        # ── Invidious fallback on exception ─────────────────────────────────
        LOGGER.warning("yt-dlp get_video_info raised exception — trying Invidious: %s", exc)
        try:
            loop2 = asyncio.get_event_loop()
            info = await loop2.run_in_executor(None, _invidious_search_sync, url_or_query)
            if info and info.get("id"):
                vid = info["id"]
                return {
                    "id": vid,
                    "title": info.get("title", "Unknown"),
                    "duration": int(info.get("duration") or 0),
                    "url": info.get("webpage_url") or f"https://www.youtube.com/watch?v={vid}",
                    "stream_url": "",
                    "thumbnail": info.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                    "uploader": info.get("uploader") or "Unknown",
                }
        except Exception:
            pass
        await send_error_log("get_video_info failed", exc)
        return None


# ─────────────────────────────────────────────────────────────────────────────
#  FIFO pipe streaming  (⚡ Instant play — music starts before full download)
# ─────────────────────────────────────────────────────────────────────────────

def _start_pipe_download(video_id: str, audio_only: bool = True) -> str:
    """Start yt-dlp writing audio to a FIFO named pipe in a daemon thread.
    Returns the pipe path IMMEDIATELY — yt-dlp runs in the background.

    HOW IT SAVES TIME:
    • PyTgCalls opens the FIFO path from MediaStream().
    • yt-dlp starts downloading fragments and writing bytes continuously.
    • ffmpeg inside PyTgCalls reads as bytes arrive — music starts playing
      within ~2-3 s without waiting for the full file to download.

    Falls back: callers catch OSError when mkfifo is unavailable.
    """
    tmpdir = tempfile.mkdtemp(prefix="melody_pipe_")
    pipe_path = os.path.join(tmpdir, "audio.webm")
    try:
        os.mkfifo(pipe_path)
    except OSError as err:
        shutil.rmtree(tmpdir, ignore_errors=True)
        raise OSError(
            f"FIFO not supported on this platform ({err}). "
            "Falling back to full file download."
        ) from err

    url = f"https://www.youtube.com/watch?v={video_id}"
    fmt = (
        "bestaudio[ext=webm]/bestaudio[ext=opus]/bestaudio/best"
        if audio_only
        else "best[height<=720][vcodec!=none][acodec!=none]/best[height<=720]/best"
    )

    # Build a self-contained Python script that writes audio to stdout.
    # Running as a subprocess subprocess inherits sys.path but is isolated,
    # which avoids blocking the asyncio event loop.
    cookie_line = (
        f'    opts["cookiefile"] = {repr(COOKIES_FILE)}\n'
        if os.path.exists(COOKIES_FILE) else ""
    )
    script = (
        "import sys, yt_dlp\n"
        "opts = {\n"
        f'    "format": {repr(fmt)},\n'
        '    "outtmpl": "-",\n'
        '    "quiet": True,\n'
        '    "no_warnings": True,\n'
        '    "noplaylist": True,\n'
        '    "geo_bypass": True,\n'
        '    "geo_bypass_country": "US",\n'
        '    "socket_timeout": 10,\n'
        '    "retries": 5,\n'
        '    "fragment_retries": 5,\n'
        '    "check_formats": False,\n'
        # Sequential fragments for continuous pipe flow (see _ydl_opts doc)
        '    "concurrent_fragment_downloads": 1,\n'
        '    "extractor_args": {\n'
        '        "youtube": {\n'
        '            "player_client": ["android_music", "ios", "android", "tv_embedded", "mweb", "web"],\n'
        '        }\n'
        '    },\n'
        '    "http_headers": {\n'
        '        "User-Agent": "Mozilla/5.0 (Linux; Android 13; SM-S908B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36",\n'
        '        "Referer": "https://www.youtube.com/",\n'
        '    },\n'
        "}\n"
        + cookie_line
        + f"with yt_dlp.YoutubeDL(opts) as ydl:\n"
        + f"    ydl.download([{repr(url)}])\n"
    )
    cmd = [sys.executable, "-c", script]

    with _active_pipes_lock:
        _active_pipes.add(pipe_path)

    def _writer() -> None:
        proc = None
        fifo_fd = None
        slot_acquired = False
        try:
            slot_acquired = _pipe_slots.acquire(timeout=_PIPE_SLOT_TIMEOUT)
            if not slot_acquired:
                LOGGER.warning("Pipe concurrency limit reached; abandoning FIFO | %s", video_id)
                return

            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

            # Blocking open — waits until PyTgCalls opens the read end.
            # Uses a daemon sub-thread so we can enforce a timeout.
            open_evt = threading.Event()
            open_result: list = [None]

            def _blocking_open():
                try:
                    open_result[0] = os.open(pipe_path, os.O_WRONLY)
                except Exception as e:
                    open_result[0] = e
                finally:
                    open_evt.set()

            t = threading.Thread(target=_blocking_open, daemon=True, name="melody-fifo-opener")
            t.start()

            deadline = time.monotonic() + _PIPE_CONNECT_TIMEOUT
            while not open_evt.wait(timeout=0.3):
                if time.monotonic() >= deadline:
                    LOGGER.warning("FIFO reader did not connect in %.1fs | %s", _PIPE_CONNECT_TIMEOUT, video_id)
                    try:
                        dummy = os.open(pipe_path, os.O_RDONLY | os.O_NONBLOCK)
                        os.close(dummy)
                    except Exception:
                        pass
                    return

            if isinstance(open_result[0], Exception):
                raise open_result[0]
            fifo_fd = open_result[0]

            # Relay yt-dlp stdout → FIFO directly (webm/opus passthrough, no re-encode)
            with os.fdopen(fifo_fd, "wb") as fifo:
                fifo_fd = None  # fdopen owns the fd now
                while True:
                    chunk = proc.stdout.read(65536)
                    if not chunk:
                        break
                    try:
                        fifo.write(chunk)
                    except (BrokenPipeError, OSError):
                        break

        except Exception as e:
            LOGGER.debug("FIFO writer error for %s: %s", video_id, e)
        finally:
            if fifo_fd is not None:
                try:
                    os.close(fifo_fd)
                except Exception:
                    pass
            if proc is not None:
                try:
                    proc.kill()
                    proc.wait(timeout=3)
                except Exception:
                    pass
            if slot_acquired:
                _pipe_slots.release()
            with _active_pipes_lock:
                _active_pipes.discard(pipe_path)
            try:
                shutil.rmtree(tmpdir, ignore_errors=True)
            except Exception:
                pass

    threading.Thread(target=_writer, daemon=True, name=f"melody-pipe-{video_id[:8]}").start()
    return pipe_path


# ─────────────────────────────────────────────────────────────────────────────
#  Full file download (fallback for when FIFO is unavailable or pipe fails)
# ─────────────────────────────────────────────────────────────────────────────

def _download_audio_sync(video_id: str, audio_only: bool = True) -> str:
    """Synchronous full-file download — used as fallback when FIFO unavailable."""
    url = f"https://www.youtube.com/watch?v={video_id}"
    outtmpl = f"/tmp/melody_{video_id}.%(ext)s"
    opts = {
        **_ydl_opts(audio_only=audio_only),
        "outtmpl": outtmpl,
        "extract_flat": False,
    }
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        filepath = ydl.prepare_filename(info)
    if not os.path.exists(filepath):
        found = glob.glob(f"/tmp/melody_{video_id}.*")
        if found:
            return found[0]
        raise FileNotFoundError(f"Downloaded file not found for video_id={video_id}")
    return filepath


async def download_audio(video_id: str, audio_only: bool = True) -> str:
    """Return a path to play audio from.

    Strategy:
    1. Check /tmp cache (already downloaded file) — instant.
    2. On cloud/Heroku: use FIFO pipe streaming (music starts before full download).
       • FIFO lets PyTgCalls read audio as yt-dlp writes → ~2-3 s to first sound.
    3. If FIFO not supported (rare): fall back to full file download.

    Files written to /tmp/melody_<video_id>.* are cleaned up by call.py after
    each track finishes to avoid filling the 512 MB /tmp on Heroku.
    """
    # Cache check — reuse if already downloaded
    cached = glob.glob(f"/tmp/melody_{video_id}.*")
    if cached:
        return cached[0]

    # ⚡ STREAMING: try FIFO pipe first — returns instantly, yt-dlp runs in background
    try:
        pipe_path = _start_pipe_download(video_id, audio_only=audio_only)
        LOGGER.info("⚡ Streaming via FIFO pipe | %s", video_id)
        return pipe_path
    except OSError:
        LOGGER.info("FIFO unavailable — falling back to full file download | %s", video_id)

    # Fallback: full file download (blocks until complete)
    loop = asyncio.get_running_loop()
    filepath = await loop.run_in_executor(None, _download_audio_sync, video_id, audio_only)
    return filepath


# ─────────────────────────────────────────────────────────────────────────────
#  Autoplay helpers
# ─────────────────────────────────────────────────────────────────────────────

async def get_related_videos(video_id: str, exclude_ids: list[str] = None) -> list[dict]:
    """Fetch related videos for autoplay (skip excluded IDs)."""
    exclude = set(exclude_ids or [])

    def _related():
        url = f"https://www.youtube.com/watch?v={video_id}"
        opts = {**_ydl_opts(), "extract_flat": True, "playlist_items": "1:10"}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return info.get("entries", []) if info else []

    try:
        loop = asyncio.get_running_loop()
        entries = await loop.run_in_executor(None, _related)
        results = []
        for e in entries:
            vid = e.get("id", "")
            if vid and vid not in exclude:
                results.append({
                    "id": vid,
                    "title": e.get("title", "Unknown"),
                    "duration": e.get("duration", 0),
                    "url": f"https://www.youtube.com/watch?v={vid}",
                    "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                    "uploader": e.get("uploader", "Unknown"),
                })
        return results
    except Exception as exc:
        await send_error_log("get_related_videos failed", exc)
        return []
