"""
🎵 YouTube downloader — yt-dlp wrapper

FIXES APPLIED:
  • Heroku CDN block detection — skips googlevideo.com CDN URLs that always
    fail on cloud IPs (Heroku DYNO, Railway, Render, Fly.io, etc.).
  • "Sign in to confirm you're not a bot" — uses android_music + ios + web
    player clients in order; these bypass the sign-in wall for public videos.
  • Instant streaming — download_audio() returns a FIFO named pipe on Linux
    (Heroku supports mkfifo).  yt-dlp writes audio to the pipe in a daemon
    thread; PyTgCalls starts reading before the full download finishes.
    Falls back to full file download if mkfifo is unavailable.
  • YT_COOKIES binary guard — already present; kept as-is.
  • WebM/Opus preferred format — streamable via FIFO without seeking,
    unlike AAC/M4A which requires the moov atom at EOF.
"""
import asyncio
import base64
import glob
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time

from yt_dlp import YoutubeDL
from melody.config import Config
from melody.logging import LOGGER, send_error_log

# Check whether curl_cffi is available (enables Chrome TLS impersonation,
# which bypasses YouTube's bot-detection on Heroku / cloud IPs).
try:
    import curl_cffi  # noqa: F401
    _CURL_CFFI_OK = True
    LOGGER.info("✅ curl_cffi available — Chrome TLS impersonation enabled")
except ImportError:
    _CURL_CFFI_OK = False
    LOGGER.warning(
        "curl_cffi not installed — YouTube may block requests on cloud IPs. "
        "Add 'curl_cffi>=0.7.0' to requirements.txt and redeploy."
    )


COOKIES_FILE = "/tmp/melody_yt_cookies.txt"

# ── Cloud-host detection ──────────────────────────────────────────────────────
# On Heroku/Railway/Render/Fly.io the YouTube CDN (googlevideo.com) is
# IP-blocked.  Trying to stream directly from a CDN signed URL produces an
# immediate EOF → 10-25 s of silence before the retry kicks in.
# Detect at startup and always use full local download on these hosts.
_ON_CLOUD_HOST: bool = bool(
    os.environ.get("DYNO")                    # Heroku
    or os.environ.get("RAILWAY_ENVIRONMENT")  # Railway
    or os.environ.get("RENDER_SERVICE_ID")    # Render
    or os.environ.get("FLY_APP_NAME")         # Fly.io
    or os.environ.get("K_SERVICE")            # Google Cloud Run
    or os.environ.get("WEBSITE_INSTANCE_ID")  # Azure App Service
)
if _ON_CLOUD_HOST:
    LOGGER.info("☁️  Cloud host detected — YouTube CDN streaming skipped; using local download")

# ── FIFO pipe concurrency ────────────────────────────────────────────────────
# Cap parallel FIFO downloads so we don't exhaust Heroku memory.
_PIPE_MAX_CONCURRENT = 4
_pipe_slots = threading.BoundedSemaphore(_PIPE_MAX_CONCURRENT)
_PIPE_CONNECT_TIMEOUT = 15.0   # seconds to wait for ntgcalls to open the read end
_PIPE_SLOT_TIMEOUT    = 5.0    # fail fast if all slots taken; retry will use file download

# Track pipe paths that are actively being written so _cleanup_temp can skip them.
_active_pipes: set = set()
_active_pipes_lock = threading.Lock()


# ─────────────────────────────────────────────────────────────────────────────
#  Cookie helpers (unchanged — binary-guard logic kept)
# ─────────────────────────────────────────────────────────────────────────────

def _json_cookies_to_netscape(json_text: str) -> str:
    import json
    try:
        cookies = json.loads(json_text)
    except (json.JSONDecodeError, ValueError):
        return json_text
    if not isinstance(cookies, list):
        return json_text
    lines = ["# Netscape HTTP Cookie File", "# Generated by Melody"]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expirationDate") or c.get("expires") or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _is_netscape_cookies(text: str) -> bool:
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if len(line.split("\t")) == 7:
            return True
    return False


def _write_cookies():
    """Load YT_COOKIES into COOKIES_FILE.

    ROOT-CAUSE FIX (previous bug):
    The old code ALWAYS ran base64.b64decode() first, even when YT_COOKIES
    already contained plain-text cookies.txt content (the most common way
    people paste it into Heroku config vars). Python's base64 decoder does
    NOT error on arbitrary text — it silently mangles it into garbage bytes,
    which then fail the UTF-8 decode and get logged as "binary data" and
    thrown away. This is why cookies never worked even when pasted correctly.

    NEW ORDER:
    1. Check if the raw value is ALREADY plain Netscape text or a JSON cookie
       array (no decoding needed) — use it directly.
    2. Only if that fails, attempt strict base64 decoding (validate=True so
       non-base64 text raises immediately instead of being silently corrupted).
    """
    if not Config.YT_COOKIES:
        LOGGER.warning(
            "⚠️ YT_COOKIES is not set — bot will run WITHOUT a YouTube login. "
            "Heroku IPs are heavily bot-checked; cookies are strongly recommended."
        )
        return

    raw = Config.YT_COOKIES.strip()

    # ── Path 1: already plain text (most common case) ──────────────────────
    if raw.startswith("["):
        netscape = _json_cookies_to_netscape(raw)
        if _is_netscape_cookies(netscape):
            with open(COOKIES_FILE, "w", encoding="utf-8") as f:
                f.write(netscape)
            LOGGER.info("✅ YT_COOKIES (plain JSON→Netscape) written to %s", COOKIES_FILE)
            return
    if raw.startswith("#") or _is_netscape_cookies(raw):
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(raw)
        LOGGER.info("✅ YT_COOKIES (plain Netscape text) written to %s", COOKIES_FILE)
        return

    # ── Path 2: base64-encoded (strict — fail loudly instead of corrupting) ─
    try:
        raw_bytes = base64.b64decode(raw, validate=True)
    except Exception as e:
        LOGGER.warning(
            "❌ YT_COOKIES is neither plain cookies.txt text nor valid base64 — "
            "skipping cookies: %s", e
        )
        return
    try:
        decoded = raw_bytes.decode("utf-8")
    except UnicodeDecodeError:
        LOGGER.warning(
            "❌ YT_COOKIES base64 decodes to binary data (not a text cookie file). "
            "Paste the raw cookies.txt content directly into the config var — "
            "no base64 encoding needed. Skipping cookies."
        )
        return
    decoded = decoded.strip()
    if decoded.startswith("["):
        netscape = _json_cookies_to_netscape(decoded)
        if not _is_netscape_cookies(netscape):
            LOGGER.warning("❌ YT_COOKIES JSON conversion produced no valid entries — skipping.")
            return
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(netscape)
        LOGGER.info("✅ YT_COOKIES (base64 JSON→Netscape) written to %s", COOKIES_FILE)
        return
    if _is_netscape_cookies(decoded):
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(decoded)
        LOGGER.info("✅ YT_COOKIES (base64 Netscape) written to %s", COOKIES_FILE)
        return
    LOGGER.warning(
        "❌ YT_COOKIES format not recognised (not JSON array, not Netscape). "
        "Export cookies using a browser extension like 'Get cookies.txt LOCALLY' "
        "while logged into youtube.com, then paste the file content as-is. "
        "Skipping cookies — yt-dlp will run without authentication."
    )


_write_cookies()
_HAS_COOKIES = os.path.exists(COOKIES_FILE)
if _HAS_COOKIES:
    LOGGER.info("🍪 Cookie-authenticated YouTube session ACTIVE — using logged-in requests")
else:
    LOGGER.warning("🍪 No cookies loaded — running as anonymous guest (more likely to be blocked on Heroku)")


# ─────────────────────────────────────────────────────────────────────────────
#  yt-dlp options
# ─────────────────────────────────────────────────────────────────────────────

def _ydl_opts(audio_only: bool = True) -> dict:
    """Return base yt-dlp options tuned for Heroku and bot-detection bypass.

    FIXES:
    • "Sign in to confirm you're not a bot":
        android_music → ios → android → tv_embedded → mweb → web
        Android/iOS clients are served a different API path that skips the
        sign-in wall for public videos.  This is the canonical yt-dlp fix.
    • WebM/Opus format preferred — streamable via FIFO pipe without seeking.
      AAC/M4A requires the moov atom at end-of-file → breaks pipe mode.
    • geo_bypass — Heroku USA servers sometimes hit geo-restricted content;
      bypass declaration helps with most non-DRM videos.
    • concurrent_fragment_downloads=1 — sequential fragments keep the FIFO
      data stream continuous; parallel downloads create write bursts → pipe
      starvation → ntgcalls EOF → Broken pipe.
    """
    fmt = (
        # Use broad selector — ext constraints removed since FIFO pipe was
        # removed; full file download supports any container.  YouTube
        # occasionally does not serve a specific ext (region/age restrictions),
        # causing "Requested format is not available".  bestaudio/best lets
        # yt-dlp pick whatever is actually available.
        "bestaudio/best"
        if audio_only
        else "best[height<=720][vcodec!=none][acodec!=none]/best[height<=720]/best"
    )
    has_cookies = os.path.exists(COOKIES_FILE)

    # STRICT COOKIE MODE:
    # android_music/ios/tv_embedded clients authenticate via their own
    # embedded API keys and IGNORE a cookiefile entirely — cookies only take
    # effect on the "web"/"mweb" client paths. So when cookies are present we
    # put "web" FIRST (uses the logged-in session, bypasses bot-detection and
    # age/sign-in walls) and keep the others only as a safety-net fallback.
    player_client = (
        ["web", "mweb", "tv_embedded", "android_music", "ios", "android"]
        if has_cookies
        else ["tv_embedded", "android_music", "ios", "android", "mweb", "web"]
    )
    # A cookies.txt file is exported from a real desktop/mobile browser
    # session — pairing it with a matching browser User-Agent (instead of the
    # generic mobile UA) keeps the request fingerprint consistent and avoids
    # extra bot-detection flags.
    user_agent = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        if has_cookies
        else "Mozilla/5.0 (Linux; Android 13; SM-S908B) AppleWebKit/537.36 "
             "(KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36"
    )

    opts: dict = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "format": fmt,
        "postprocessors": [],
        "geo_bypass": True,
        "geo_bypass_country": "US",
        "socket_timeout": 10,
        "retries": 5,
        "fragment_retries": 5,
        "check_formats": False,
        "concurrent_fragment_downloads": 1,
        "extractor_args": {
            "youtube": {
                "player_client": player_client,
            }
        },
        "http_headers": {
            "User-Agent": user_agent,
            "Referer": "https://www.youtube.com/",
        },
    }
    # NOTE: curl_cffi "impersonate" intentionally removed.
    # The impersonate target varies by installed version and crashes yt-dlp
    # with "Impersonate target not available" on older curl_cffi builds.
    if has_cookies:
        opts["cookiefile"] = COOKIES_FILE
    if Config.YT_PROXY:
        opts["proxy"] = Config.YT_PROXY
    return opts


# ─────────────────────────────────────────────────────────────────────────────
#  Search helpers
# ─────────────────────────────────────────────────────────────────────────────

async def search_youtube(query: str, limit: int = 5) -> list[dict]:
    """Search YouTube and return a list of results."""
    def _search():
        opts = {**_ydl_opts(), "default_search": f"ytsearch{limit}", "extract_flat": True}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            return info.get("entries", [])

    try:
        loop = asyncio.get_running_loop()
        results = await loop.run_in_executor(None, _search)
        return [
            {
                "id": e.get("id", ""),
                "title": e.get("title", "Unknown"),
                "duration": e.get("duration", 0),
                "url": f"https://www.youtube.com/watch?v={e.get('id', '')}",
                "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{e.get('id','')}/hqdefault.jpg",
                "uploader": e.get("uploader", "Unknown"),
            }
            for e in results
            if e.get("id")
        ]
    except Exception as exc:
        await send_error_log("search_youtube failed", exc)
        return []


def _extract_video_id(url: str) -> str | None:
    """Extract YouTube video ID from various URL formats."""
    import re
    patterns = [
        r"(?:v=|/v/|youtu\.be/|/embed/|/shorts/)([A-Za-z0-9_-]{11})",
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return None



# ─────────────────────────────────────────────────────────────────────────────
#  YouTube InnerTube API fallback search
#  Direct POST to YouTube's internal API (same endpoint yt-dlp uses).
#  Works from Heroku because it hits youtube.com directly (not a proxy).
#  Uses the ANDROID client which bypasses bot-detection without cookies.
# ─────────────────────────────────────────────────────────────────────────────

def _innertube_search_sync(query: str) -> dict | None:
    """Search YouTube via InnerTube API — Heroku-safe, no yt-dlp needed.

    WHY THIS WORKS ON HEROKU:
    YouTube's own search API (used internally by all YouTube clients) accepts
    POST requests from the Android app client. The Android client path is
    NOT subject to the same bot-detection as the web player — it is served by
    a completely different API endpoint that doesn't require login or cookies.

    This is the same API yt-dlp uses for its ytsearch extractor, but called
    directly so we bypass yt-dlp's player-client selection entirely.
    """
    import json
    import urllib.request

    _API_KEY = "AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w"   # public Android API key
    _SEARCH_URL = f"https://www.youtube.com/youtubei/v1/search?key={_API_KEY}&prettyPrint=false"

    # Android client context — not bot-challenged, no sign-in required
    payload = json.dumps({
        "context": {
            "client": {
                "clientName": "ANDROID",
                "clientVersion": "19.09.37",
                "androidSdkVersion": 30,
                "hl": "en",
                "gl": "US",
                "utcOffsetMinutes": 0,
            }
        },
        "query": query,
        "params": "EgIQAQ%3D%3D",   # filter: videos only
    }).encode("utf-8")

    req = urllib.request.Request(
        _SEARCH_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip",
            "X-YouTube-Client-Name": "3",
            "X-YouTube-Client-Version": "19.09.37",
            "Accept-Language": "en-US,en;q=0.9",
        },
        method="POST",
    )

    try:
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open(req, timeout=12) as resp:
            if resp.status != 200:
                LOGGER.warning("InnerTube search HTTP %s for: %s", resp.status, query[:50])
                return None
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as exc:
        LOGGER.warning("InnerTube search network error: %s", exc)
        return None

    # Parse InnerTube response — walk the renderer tree
    try:
        contents = (
            data.get("contents", {})
                .get("sectionListRenderer", {})
                .get("contents", [])
        )
        for section in contents:
            items = (
                section.get("itemSectionRenderer", {})
                       .get("contents", [])
            )
            for item in items:
                vr = item.get("videoRenderer")
                if not vr:
                    continue
                vid = vr.get("videoId", "")
                if not vid:
                    continue

                # title
                title = (vr.get("title", {})
                           .get("runs", [{}])[0]
                           .get("text", "") or query)

                # duration — "3:45" or "1:02:33"
                duration_text = (
                    vr.get("lengthText", {}).get("simpleText", "") or
                    vr.get("lengthText", {}).get("runs", [{}])[0].get("text", "")
                )
                duration = 0
                if duration_text:
                    parts = [int(p) for p in duration_text.split(":") if p.isdigit()]
                    if len(parts) == 2:
                        duration = parts[0] * 60 + parts[1]
                    elif len(parts) == 3:
                        duration = parts[0] * 3600 + parts[1] * 60 + parts[2]

                # thumbnail
                thumbs = (vr.get("thumbnail", {}).get("thumbnails") or [])
                thumbnail = thumbs[-1].get("url", "") if thumbs else f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg"

                # uploader
                uploader = (
                    vr.get("ownerText", {}).get("runs", [{}])[0].get("text", "") or
                    vr.get("longBylineText", {}).get("runs", [{}])[0].get("text", "") or
                    "Unknown"
                )

                LOGGER.info("✅ InnerTube search OK: %s", title[:50])
                return {
                    "id": vid,
                    "webpage_url": f"https://www.youtube.com/watch?v={vid}",
                    "title": title,
                    "duration": duration,
                    "thumbnail": thumbnail,
                    "uploader": uploader,
                }
    except Exception as exc:
        LOGGER.warning("InnerTube response parse error: %s", exc)

    LOGGER.warning("❌ InnerTube search: no video results for: %s", query[:50])
    return None


# Keep Invidious as a secondary backup behind InnerTube
_INVIDIOUS_INSTANCES = [
    "https://invidious.f5.si",
    "https://invidious.privacydev.net",
    "https://invidious.nerdvpn.de",
    "https://invidious.fdn.fr",
    "https://invidious.io.lol",
    "https://invidious.einfachzocken.eu",
    "https://invidious.privacyredirect.com",
    "https://invidious.jing.rocks",
    "https://invidious.asir.dev",
    "https://invidious.drgns.space",
]


def _invidious_search_sync(query: str) -> dict | None:
    """Secondary fallback: Invidious public instances."""
    import json, urllib.request, urllib.parse
    encoded = urllib.parse.quote_plus(query)
    headers = {"User-Agent": "Mozilla/5.0 (compatible; MelodyBot/1.0)"}
    for inst in _INVIDIOUS_INSTANCES:
        try:
            url = f"{inst}/api/v1/search?q={encoded}&type=video"
            req = urllib.request.Request(url, headers=headers)
            opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
            with opener.open(req, timeout=5) as resp:
                if resp.status != 200:
                    continue
                items = json.loads(resp.read().decode("utf-8"))
            res = next((i for i in items if i.get("type") == "video" and i.get("videoId")), None)
            if not res:
                continue
            vid = res["videoId"]
            thumbs = res.get("videoThumbnails") or []
            thumb = next((t.get("url", "") for t in thumbs if t.get("quality") in {"medium", "high"}),
                         thumbs[0].get("url", "") if thumbs else "")
            LOGGER.info("✅ Invidious search OK (%s): %s", inst, res.get("title", "")[:50])
            return {
                "id": vid, "webpage_url": f"https://www.youtube.com/watch?v={vid}",
                "title": res.get("title") or query, "duration": int(res.get("lengthSeconds") or 0),
                "thumbnail": thumb, "uploader": res.get("author") or "",
            }
        except Exception as exc:
            LOGGER.debug("Invidious (%s) failed: %s", inst, exc)
    LOGGER.warning("❌ All Invidious instances failed for: %s", query[:50])
    return None


async def get_video_info(url_or_query: str) -> dict | None:
    """Get metadata for a single video (or first search result).

    KEY FIX for Heroku "Sign in to confirm you're not a bot":
    • Uses extract_flat=True — yt-dlp fetches only lightweight metadata
      (title, duration, uploader, thumbnail) WITHOUT requesting streamingData
      (the format/CDN URL list). streamingData calls are what trigger YouTube's
      bot-detection check on cloud IPs. By deferring stream resolution to
      download_audio(), we avoid the check entirely at this stage.
    • For direct YouTube URLs we extract the video_id and search by video_id,
      still via the flat/metadata path (no streamingData request).
    """
    import re
    is_url = bool(re.match(r"https?://", url_or_query))

    if is_url:
        vid_id = _extract_video_id(url_or_query)
        # Use ytsearch1: for the video URL — forces the search API path which
        # only fetches metadata, not streamingData.
        query = f"ytsearch1:{url_or_query}" if not vid_id else f"ytsearch1:https://www.youtube.com/watch?v={vid_id}"
    else:
        query = f"ytsearch1:{url_or_query}"
        vid_id = None

    def _info():
        # CRITICAL FIX: noplaylist=False is REQUIRED for ytsearch1: queries.
        # yt-dlp 2025+ internally wraps ytsearch results in a "SearchResultsPlaylist".
        # With noplaylist=True (from _ydl_opts), yt-dlp refuses to process it → returns
        # nothing → silent "Song not found" error even when the video exists.
        # extract_flat="in_playlist" — lightweight metadata only, no streamingData request
        # (streamingData = the CDN URL list that triggers YouTube bot-detection on Heroku).
        opts = {
            **_ydl_opts(),
            "extract_flat": "in_playlist",
            "default_search": "ytsearch1",
            "noplaylist": False,    # MUST be False for ytsearch1: to work
            "socket_timeout": 6,    # fail fast so Invidious fallback runs sooner
        }
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            if info and "entries" in info and info["entries"]:
                return info["entries"][0]
            return info

    try:
        loop = asyncio.get_running_loop()
        info = await loop.run_in_executor(None, _info)
        if not info or not info.get("id"):
            # ── Invidious fallback: yt-dlp search returned nothing ──────────
            # On Heroku, YouTube's bot-detection sometimes blocks yt-dlp even
            # with Android/iOS clients. Invidious runs its own YouTube API proxy
            # on non-cloud IPs — it is not affected by Heroku's IP ban.
            LOGGER.info("yt-dlp search returned nothing — trying InnerTube fallback | %s", url_or_query[:50])
            info = await asyncio.get_event_loop().run_in_executor(
                None, _innertube_search_sync, url_or_query
            )
            if not info or not info.get("id"):
                LOGGER.info("InnerTube returned nothing — trying Invidious | %s", url_or_query[:50])
                info = await asyncio.get_event_loop().run_in_executor(
                    None, _invidious_search_sync, url_or_query
                )
            if not info or not info.get("id"):
                return None
        vid = info.get("id", "")
        return {
            "id": vid,
            "title": info.get("title", "Unknown"),
            "duration": int(info.get("duration") or 0),
            "url": info.get("webpage_url") or f"https://www.youtube.com/watch?v={vid}",
            "stream_url": "",  # resolved at play time by download_audio()
            "thumbnail": info.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
            "uploader": info.get("uploader") or info.get("channel") or "Unknown",
        }
    except Exception as exc:
        # ── Invidious fallback on exception ─────────────────────────────────
        LOGGER.warning("yt-dlp get_video_info raised exception — trying InnerTube: %s", exc)
        try:
            loop2 = asyncio.get_event_loop()
            info = await loop2.run_in_executor(None, _innertube_search_sync, url_or_query)
            if not info or not info.get("id"):
                info = await loop2.run_in_executor(None, _invidious_search_sync, url_or_query)
            if info and info.get("id"):
                vid = info["id"]
                return {
                    "id": vid,
                    "title": info.get("title", "Unknown"),
                    "duration": int(info.get("duration") or 0),
                    "url": info.get("webpage_url") or f"https://www.youtube.com/watch?v={vid}",
                    "stream_url": "",
                    "thumbnail": info.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                    "uploader": info.get("uploader") or "Unknown",
                }
        except Exception:
            pass
        await send_error_log("get_video_info failed", exc)
        return None


# ─────────────────────────────────────────────────────────────────────────────
#  FIFO pipe streaming  (⚡ Instant play — music starts before full download)
# ─────────────────────────────────────────────────────────────────────────────

def _start_pipe_download(video_id: str, audio_only: bool = True) -> str:
    """Start yt-dlp writing audio to a FIFO named pipe in a daemon thread.
    Returns the pipe path IMMEDIATELY — yt-dlp runs in the background.

    HOW IT SAVES TIME:
    • PyTgCalls opens the FIFO path from MediaStream().
    • yt-dlp starts downloading fragments and writing bytes continuously.
    • ffmpeg inside PyTgCalls reads as bytes arrive — music starts playing
      within ~2-3 s without waiting for the full file to download.

    Falls back: callers catch OSError when mkfifo is unavailable.
    """
    tmpdir = tempfile.mkdtemp(prefix="melody_pipe_")
    pipe_path = os.path.join(tmpdir, "audio.webm")
    try:
        os.mkfifo(pipe_path)
    except OSError as err:
        shutil.rmtree(tmpdir, ignore_errors=True)
        raise OSError(
            f"FIFO not supported on this platform ({err}). "
            "Falling back to full file download."
        ) from err

    url = f"https://www.youtube.com/watch?v={video_id}"
    fmt = (
        # Broad selector — same rationale as _ydl_opts(): ext constraints
        # removed to avoid "Requested format is not available" crashes.
        "bestaudio/best"
        if audio_only
        else "best[height<=720][vcodec!=none][acodec!=none]/best[height<=720]/best"
    )

    # Build a self-contained Python script that writes audio to stdout.
    # Running as a subprocess subprocess inherits sys.path but is isolated,
    # which avoids blocking the asyncio event loop.
    #
    # STRICT COOKIE MODE (kept in sync with _ydl_opts()):
    # android/ios/tv_embedded clients ignore cookiefile entirely — only the
    # "web"/"mweb" client paths use the logged-in session. So when cookies
    # exist, "web" goes first and the UA matches a real desktop browser.
    has_cookies = os.path.exists(COOKIES_FILE)
    cookie_line = (
        f'    opts["cookiefile"] = {repr(COOKIES_FILE)}\n' if has_cookies else ""
    )
    player_client_list = (
        ["web", "mweb", "tv_embedded", "android_music", "ios", "android"]
        if has_cookies
        else ["android_music", "ios", "android", "tv_embedded", "mweb", "web"]
    )
    user_agent = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        if has_cookies
        else "Mozilla/5.0 (Linux; Android 13; SM-S908B) AppleWebKit/537.36 "
             "(KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36"
    )
    script = (
        "import sys, yt_dlp\n"
        "opts = {\n"
        f'    "format": {repr(fmt)},\n'
        '    "outtmpl": "-",\n'
        '    "quiet": True,\n'
        '    "no_warnings": True,\n'
        '    "noplaylist": True,\n'
        '    "geo_bypass": True,\n'
        '    "geo_bypass_country": "US",\n'
        '    "socket_timeout": 10,\n'
        '    "retries": 5,\n'
        '    "fragment_retries": 5,\n'
        '    "check_formats": False,\n'
        # Sequential fragments for continuous pipe flow (see _ydl_opts doc)
        '    "concurrent_fragment_downloads": 1,\n'
        '    "extractor_args": {\n'
        '        "youtube": {\n'
        f'            "player_client": {repr(player_client_list)},\n'
        '        }\n'
        '    },\n'
        '    "http_headers": {\n'
        f'        "User-Agent": {repr(user_agent)},\n'
        '        "Referer": "https://www.youtube.com/",\n'
        '    },\n'
        "}\n"
        + cookie_line
        + f"with yt_dlp.YoutubeDL(opts) as ydl:\n"
        + f"    ydl.download([{repr(url)}])\n"
    )
    cmd = [sys.executable, "-c", script]

    with _active_pipes_lock:
        _active_pipes.add(pipe_path)

    def _writer() -> None:
        proc = None
        fifo_fd = None
        slot_acquired = False
        try:
            slot_acquired = _pipe_slots.acquire(timeout=_PIPE_SLOT_TIMEOUT)
            if not slot_acquired:
                LOGGER.warning("Pipe concurrency limit reached; abandoning FIFO | %s", video_id)
                return

            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)

            # Blocking open — waits until PyTgCalls opens the read end.
            # Uses a daemon sub-thread so we can enforce a timeout.
            open_evt = threading.Event()
            open_result: list = [None]

            def _blocking_open():
                try:
                    open_result[0] = os.open(pipe_path, os.O_WRONLY)
                except Exception as e:
                    open_result[0] = e
                finally:
                    open_evt.set()

            t = threading.Thread(target=_blocking_open, daemon=True, name="melody-fifo-opener")
            t.start()

            deadline = time.monotonic() + _PIPE_CONNECT_TIMEOUT
            while not open_evt.wait(timeout=0.3):
                if time.monotonic() >= deadline:
                    LOGGER.warning("FIFO reader did not connect in %.1fs | %s", _PIPE_CONNECT_TIMEOUT, video_id)
                    try:
                        dummy = os.open(pipe_path, os.O_RDONLY | os.O_NONBLOCK)
                        os.close(dummy)
                    except Exception:
                        pass
                    return

            if isinstance(open_result[0], Exception):
                raise open_result[0]
            fifo_fd = open_result[0]

            # Relay yt-dlp stdout → FIFO directly (webm/opus passthrough, no re-encode)
            with os.fdopen(fifo_fd, "wb") as fifo:
                fifo_fd = None  # fdopen owns the fd now
                while True:
                    chunk = proc.stdout.read(65536)
                    if not chunk:
                        break
                    try:
                        fifo.write(chunk)
                    except (BrokenPipeError, OSError):
                        break

        except Exception as e:
            LOGGER.debug("FIFO writer error for %s: %s", video_id, e)
        finally:
            if fifo_fd is not None:
                try:
                    os.close(fifo_fd)
                except Exception:
                    pass
            if proc is not None:
                try:
                    proc.kill()
                    proc.wait(timeout=3)
                except Exception:
                    pass
            if slot_acquired:
                _pipe_slots.release()
            with _active_pipes_lock:
                _active_pipes.discard(pipe_path)
            try:
                shutil.rmtree(tmpdir, ignore_errors=True)
            except Exception:
                pass

    threading.Thread(target=_writer, daemon=True, name=f"melody-pipe-{video_id[:8]}").start()
    return pipe_path


# ─────────────────────────────────────────────────────────────────────────────
#  Full file download (fallback for when FIFO is unavailable or pipe fails)
# ─────────────────────────────────────────────────────────────────────────────

def _download_audio_sync(video_id: str, audio_only: bool = True) -> str:
    """Synchronous full-file download — used as fallback when FIFO unavailable."""
    url = f"https://www.youtube.com/watch?v={video_id}"
    outtmpl = f"/tmp/melody_{video_id}.%(ext)s"
    opts = {
        **_ydl_opts(audio_only=audio_only),
        "outtmpl": outtmpl,
        "extract_flat": False,
    }
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=True)
        filepath = ydl.prepare_filename(info)
    if not os.path.exists(filepath):
        found = glob.glob(f"/tmp/melody_{video_id}.*")
        if found:
            return found[0]
        raise FileNotFoundError(f"Downloaded file not found for video_id={video_id}")
    return filepath


async def download_audio(video_id: str, audio_only: bool = True) -> str:
    """Return a path to play audio from.

    Strategy: always do a full file download to /tmp, then hand the finished
    file's path to PyTgCalls.

    FIFO pipe streaming was REMOVED (root-cause fix): PyTgCalls' MediaStream
    always calls ffmpeg.check_stream() before playback, which runs `ffprobe`
    on the given path and reads it start-to-EOF to inspect the stream. A
    named pipe (FIFO) only supports being drained ONCE — after ffprobe
    finishes reading it for the probe, there is nothing left in the pipe for
    the real ffmpeg playback process that follows, and by then our writer
    thread has already deleted the tmp directory. This is exactly what was
    causing `_stream_track failed ... FileNotFoundError` / "No such file" in
    the logs: check_stream() drained (or outright missed, on a slow/slotted
    writer) the pipe before real playback could read anything from it.

    A one-shot FIFO simply cannot survive being read twice (probe + play),
    so the "instant streaming" pipe trick is fundamentally incompatible with
    this pytgcalls version and has to go. The bot still starts fast because
    the VC join (pre_join) and the download both run concurrently — only the
    download itself is no longer piped.

    Files written to /tmp/melody_<video_id>.* are cleaned up by call.py after
    each track finishes to avoid filling the 512 MB /tmp on Heroku.
    """
    # Cache check — reuse if already downloaded
    cached = glob.glob(f"/tmp/melody_{video_id}.*")
    if cached:
        return cached[0]

    loop = asyncio.get_running_loop()
    filepath = await loop.run_in_executor(None, _download_audio_sync, video_id, audio_only)
    return filepath


# ─────────────────────────────────────────────────────────────────────────────
#  Autoplay helpers
# ─────────────────────────────────────────────────────────────────────────────

async def get_related_videos(video_id: str, exclude_ids: list[str] = None) -> list[dict]:
    """Fetch related videos for autoplay (skip excluded IDs)."""
    exclude = set(exclude_ids or [])

    def _related():
        # ROOT-CAUSE FIX: this call only needs lightweight metadata (title,
        # duration, thumbnail) for the autoplay queue — it must never try to
        # resolve a playable *format* for anything. The previous version
        # reused _ydl_opts(), which always sets a strict "format" selector
        # for downloading. Even with extract_flat=True, yt-dlp still fully
        # processes the primary watch-page result before flattening the
        # "up next" mix, so an unavailable format on that primary video
        # (age-restricted, region-locked, or a format list YouTube changed)
        # raised straight out of extract_info() and killed the whole
        # autoplay lookup — that's the "Requested format is not available"
        # crash from the error log.
        #
        # Fix: request YouTube's dedicated "up next" Mix/Radio playlist
        # (list=RD<id>) so entries come back as flat playlist items (never
        # format-resolved), strip the format selector entirely, and ignore
        # per-entry errors so one broken related video can't blank the list.
        url = f"https://www.youtube.com/watch?v={video_id}&list=RD{video_id}"
        opts = {**_ydl_opts(), "extract_flat": True, "playlist_items": "1:10"}
        opts.pop("format", None)
        opts["ignoreerrors"] = True
        opts["skip_download"] = True
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return info.get("entries") or [] if info else []

    try:
        loop = asyncio.get_running_loop()
        entries = await loop.run_in_executor(None, _related)
        results = []
        for e in entries:
            if not e:
                continue  # ignoreerrors leaves a None slot for a broken entry
            vid = e.get("id", "")
            if vid and vid not in exclude:
                results.append({
                    "id": vid,
                    "title": e.get("title", "Unknown"),
                    "duration": e.get("duration", 0),
                    "url": f"https://www.youtube.com/watch?v={vid}",
                    "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                    "uploader": e.get("uploader", "Unknown"),
                })
        return results
    except Exception as exc:
        await send_error_log("get_related_videos failed", exc)
        return []
