"""
🎵 YouTube downloader — yt-dlp wrapper
"""
import asyncio
import base64
import glob
import os
import re
from yt_dlp import YoutubeDL
from melody.config import Config
from melody.logging import LOGGER, send_error_log


COOKIES_FILE = "/tmp/melody_yt_cookies.txt"


def _json_cookies_to_netscape(json_text: str) -> str:
    """Convert a JSON cookie array (browser export) to Netscape cookie format.

    BUG FIX: yt-dlp requires cookies in Netscape format. Browser extensions
    (e.g. "Get cookies.txt LOCALLY") can export JSON arrays. Storing that
    JSON as-is caused yt-dlp to print:
        ERROR: Cookies file must be Netscape formatted, not JSON.
    This function detects JSON input and converts it so yt-dlp can read it.

    Netscape format columns (tab-separated):
        domain  include_subdomains  path  secure  expiry  name  value
    """
    import json
    try:
        cookies = json.loads(json_text)
    except (json.JSONDecodeError, ValueError):
        # Not JSON — return as-is (already Netscape or other format)
        return json_text

    if not isinstance(cookies, list):
        return json_text

    lines = ["# Netscape HTTP Cookie File", "# Generated by Melody"]
    for c in cookies:
        domain = c.get("domain", "")
        # include_subdomains: TRUE when domain starts with "."
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # expirationDate from Chrome JSON; "expires" from Firefox JSON
        expiry = int(c.get("expirationDate") or c.get("expires") or 0)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

    return "\n".join(lines) + "\n"


def _is_netscape_cookies(text: str) -> bool:
    """Return True if text looks like a valid Netscape cookie file."""
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Every data line must have exactly 7 tab-separated fields
        if len(line.split("\t")) == 7:
            return True
    return False


def _write_cookies():
    """Decode base64 YT_COOKIES and write a valid Netscape file for yt-dlp.

    ROOT-CAUSE FIX for recurring "Cookies file must be Netscape formatted"
    yt-dlp errors:

    The previous code decoded the base64 env var and wrote whatever came out,
    even if the result was binary garbage (e.g. a raw Chrome SQLite cookies DB,
    a Firefox cookies.sqlite, or a corrupted export).  yt-dlp strictly expects
    Netscape HTTP Cookie File format — any other content causes:
        ERROR: Cookies file must be Netscape formatted, not JSON.
        WARNING: skipping cookie file entry due to invalid length 1: ...

    Fix strategy (in order):
    1. Detect binary content early — if the decoded text contains UTF-8
       replacement characters (U+FFFD), the base64 decoded to non-text binary.
       Don't write the file; yt-dlp will just run without cookies.
    2. Detect JSON array (browser extension exports like "Get cookies.txt") —
       convert to Netscape format automatically.
    3. Detect already-valid Netscape content — write as-is.
    4. Anything else — skip writing and warn; running without cookies is
       better than crashing yt-dlp with a broken file every request.
    """
    if not Config.YT_COOKIES:
        return

    try:
        raw_bytes = base64.b64decode(Config.YT_COOKIES)
    except Exception as e:
        LOGGER.warning("YT_COOKIES is not valid base64 — skipping cookies: %s", e)
        return

    # Step 1: detect binary — try strict UTF-8 decode first
    try:
        decoded = raw_bytes.decode("utf-8")
    except UnicodeDecodeError:
        LOGGER.warning(
            "YT_COOKIES base64 decodes to binary data (not a text cookie file). "
            "Provide a Netscape-formatted cookies.txt exported from your browser. "
            "Skipping cookies — yt-dlp will run without authentication."
        )
        return

    # Extra guard: errors="replace" replacement char means hidden binary
    if "\ufffd" in decoded:
        LOGGER.warning(
            "YT_COOKIES contains non-UTF-8 bytes (binary file). "
            "Export cookies as Netscape text (not a SQLite DB). "
            "Skipping cookies."
        )
        return

    decoded = decoded.strip()

    # Step 2: JSON cookie array → Netscape conversion
    if decoded.startswith("["):
        netscape = _json_cookies_to_netscape(decoded)
        if not _is_netscape_cookies(netscape):
            LOGGER.warning("YT_COOKIES JSON conversion produced no valid entries — skipping.")
            return
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(netscape)
        LOGGER.info("YT_COOKIES (JSON→Netscape) written to %s", COOKIES_FILE)
        return

    # Step 3: already Netscape
    if _is_netscape_cookies(decoded):
        with open(COOKIES_FILE, "w", encoding="utf-8") as f:
            f.write(decoded)
        LOGGER.info("YT_COOKIES (Netscape) written to %s", COOKIES_FILE)
        return

    # Step 4: unrecognised format — don't write garbage
    LOGGER.warning(
        "YT_COOKIES format not recognised (not JSON array, not Netscape). "
        "Export cookies using a browser extension like 'Get cookies.txt LOCALLY'. "
        "Skipping cookies — yt-dlp will run without authentication."
    )


_write_cookies()


def _ydl_opts(audio_only: bool = True) -> dict:
    opts = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "format": "bestaudio/best" if audio_only else "best[height<=720]",
        "postprocessors": [],
    }
    if os.path.exists(COOKIES_FILE):
        opts["cookiefile"] = COOKIES_FILE
    return opts


async def search_youtube(query: str, limit: int = 5) -> list[dict]:
    """Search YouTube and return a list of results."""
    def _search():
        opts = {**_ydl_opts(), "default_search": f"ytsearch{limit}", "extract_flat": True}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            return info.get("entries", [])

    try:
        loop = asyncio.get_running_loop()
        results = await loop.run_in_executor(None, _search)
        return [
            {
                "id": e.get("id", ""),
                "title": e.get("title", "Unknown"),
                "duration": e.get("duration", 0),
                "url": f"https://www.youtube.com/watch?v={e.get('id', '')}",
                "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{e.get('id','')}/hqdefault.jpg",
                "uploader": e.get("uploader", "Unknown"),
            }
            for e in results
            if e.get("id")
        ]
    except Exception as exc:
        await send_error_log("search_youtube failed", exc)
        return []


async def get_video_info(url_or_query: str) -> dict | None:
    """Get info for a single video (or first search result)."""
    is_url = re.match(r"https?://", url_or_query)
    query = url_or_query if is_url else f"ytsearch1:{url_or_query}"

    def _info():
        opts = {**_ydl_opts(), "extract_flat": False}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(query, download=False)
            if "entries" in info:
                info = info["entries"][0]
            return info

    try:
        loop = asyncio.get_running_loop()
        info = await loop.run_in_executor(None, _info)
        return {
            "id": info.get("id", ""),
            "title": info.get("title", "Unknown"),
            "duration": info.get("duration", 0),
            "url": info.get("webpage_url") or f"https://www.youtube.com/watch?v={info.get('id','')}",
            "stream_url": "",  # not used; audio is downloaded at play time via download_audio()
            "thumbnail": info.get("thumbnail") or f"https://i.ytimg.com/vi/{info.get('id','')}/hqdefault.jpg",
            "uploader": info.get("uploader", "Unknown"),
        }
    except Exception as exc:
        await send_error_log("get_video_info failed", exc)
        return None


async def download_audio(video_id: str) -> str:
    """Download audio for a video_id to /tmp/ and return the local file path.

    Uses a cache: if the file is already downloaded, returns the cached path.
    Files are deleted by call.py after each track finishes to save /tmp space.
    """
    # Check cache first
    cached = glob.glob(f"/tmp/melody_{video_id}.*")
    if cached:
        return cached[0]

    url = f"https://www.youtube.com/watch?v={video_id}"
    outtmpl = f"/tmp/melody_{video_id}.%(ext)s"

    def _download():
        opts = {
            **_ydl_opts(audio_only=True),
            "outtmpl": outtmpl,
            "extract_flat": False,
        }
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=True)
            return ydl.prepare_filename(info)

    loop = asyncio.get_running_loop()
    filepath = await loop.run_in_executor(None, _download)

    # prepare_filename may not include the actual ext if postprocessing renamed it
    if not os.path.exists(filepath):
        found = glob.glob(f"/tmp/melody_{video_id}.*")
        if found:
            filepath = found[0]
        else:
            raise FileNotFoundError(f"Downloaded file not found for video_id={video_id}")

    return filepath


async def get_related_videos(video_id: str, exclude_ids: list[str] = None) -> list[dict]:
    """Fetch related videos for autoplay (skip excluded IDs)."""
    exclude = set(exclude_ids or [])

    def _related():
        url = f"https://www.youtube.com/watch?v={video_id}"
        opts = {**_ydl_opts(), "extract_flat": True, "playlist_items": "1:10"}
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            return info.get("entries", []) if info else []

    try:
        loop = asyncio.get_running_loop()
        entries = await loop.run_in_executor(None, _related)
        results = []
        for e in entries:
            vid = e.get("id", "")
            if vid and vid not in exclude:
                results.append({
                    "id": vid,
                    "title": e.get("title", "Unknown"),
                    "duration": e.get("duration", 0),
                    "url": f"https://www.youtube.com/watch?v={vid}",
                    "thumbnail": e.get("thumbnail") or f"https://i.ytimg.com/vi/{vid}/hqdefault.jpg",
                    "uploader": e.get("uploader", "Unknown"),
                })
        return results
    except Exception as exc:
        await send_error_log("get_related_videos failed", exc)
        return []
